Principle sends invalid config to hacluster
When requesting hacluster manage an init service the principle
sends options to hacluster but is currently erroneously sending
the word 'param' as well. eg

The pinciple is setting:
''res_designate_haproxy'': ''  params op monitor interval="5s"''

When it should be:
''res_designate_haproxy'': ''op monitor interval="5s"''

Including the word 'params' evenutally causes hacluster to fail with:
ERROR: syntax in primitive: params op monitor interval=5s

Change-Id: Id35bb22692914dc3f94465d8ae7d62971a238d4e